In [61]:
import pandas as pd

In [62]:
df=pd.read_csv("IT_Job_Roles_Skills.csv")

In [63]:
df.head()

,Job Title,Job Description,Skills,Certifications
0,Admin Big Data,Responsible for managing and overseeing big da...,"Hadoop, Spark, MapReduce, Data Lakes, Data War...","Cloudera Certified Professional (CCP), Hortonw..."
1,Ansible Operations Engineer,Focuses on automating IT processes using Ansib...,"Ansible, Linux, Automation, Cloud Platforms, C...",Red Hat Certified Specialist in Ansible Automa...
2,Artifactory Administrator,Manages the Artifactory repository for build a...,"Artifactory, CI/CD, Jenkins, Docker, Maven, Gr...","JFrog Artifactory Certification, DevOps Instit..."
3,Artificial Intelligence / Machine Learning Leader,"Leads AI/ML projects and teams, defining strat...","AI Strategy, Machine Learning, Team Management...","AI-900: Microsoft Azure AI Fundamentals, Certi..."
4,Artificial Intelligence / Machine Learning Sr....,Senior role overseeing multiple AI/ML initiati...,"AI Strategy, Machine Learning, Team Management...",Certified Artificial Intelligence Practitioner...

In [64]:
df=df.dropna(subset=["Skills"])

In [65]:
df["Skills"] = df["Skills"].str.lower()
df["Job Description"] = df["Job Description"].str.lower()
df["Job Title"] = df["Job Title"].str.lower()

In [66]:
df=df.drop("Certifications",axis=1)
df=df.drop_duplicates()

In [67]:
df.describe()

,Job Title,Job Description,Skills
count,486,486,486
unique,352,463,440
top,admin big data,implements and manages security measures to pr...,"javascript, java, python, git, sql, html, css,..."
freq,2,4,8

In [68]:
df["Job Title"].value_counts()

Job Title
admin big data                               2
gcp devops engineer                          2
frameworks specialist                        2
front end developer                          2
full stack developer                         2
                                            ..
help desk technician                         1
identity and access management specialist    1
infrastructure architect                     1
internet of things (iot) developer           1
business intelligence developer              1
Name: count, Length: 352, dtype: int64

In [69]:
df["combined_text"] = (
    df["Job Title"] + " " +
    df["Skills"] + " " +
    df["Job Description"]
)

In [70]:
df.head()

,Job Title,Job Description,Skills,combined_text
0,admin big data,responsible for managing and overseeing big da...,"hadoop, spark, mapreduce, data lakes, data war...","admin big data hadoop, spark, mapreduce, data ..."
1,ansible operations engineer,focuses on automating it processes using ansib...,"ansible, linux, automation, cloud platforms, c...","ansible operations engineer ansible, linux, au..."
2,artifactory administrator,manages the artifactory repository for build a...,"artifactory, ci/cd, jenkins, docker, maven, gr...","artifactory administrator artifactory, ci/cd, ..."
3,artificial intelligence / machine learning leader,"leads ai/ml projects and teams, defining strat...","ai strategy, machine learning, team management...",artificial intelligence / machine learning lea...
4,artificial intelligence / machine learning sr....,senior role overseeing multiple ai/ml initiati...,"ai strategy, machine learning, team management...",artificial intelligence / machine learning sr....

In [73]:
df.to_csv("dataset.csv")